"""End-to-end integration test: ClaudeResearchStage through the orchestrator.

Uses a fake Claude adapter (no subprocess) to drive the full Stage flow:
prompt construction, options assembly, AttemptResult population, state
persistence. Verifies bit-equivalence with the legacy run_batch.py output
shape (state json fields, output filename pattern).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import pytest

from mantis_research.core.config import load_batch_config
from mantis_research.core.state import ClaudeResearchState, TopicStatus
from mantis_research.interface.adapters.claude_cli import (
    ClaudeCliOptions,
    ClaudeCliResult,
)
from mantis_research.interface.orchestrator import Orchestrator
from mantis_research.interface.stages.claude_research import ClaudeResearchStage

if TYPE_CHECKING:
    from pathlib import Path


@dataclass
class FakeClaudeAdapter:
    """In-memory Claude adapter — writes the expected output file on success."""

    name: str = 'fake_claude_cli'
    binary: str = '/fake/claude'
    succeed: bool = True
    raw_output: str = ''
    error: str | None = None
    duration_s: float = 1.0
    output_content: str = '# fake research brief\n\nGenerated by FakeClaudeAdapter.\n'
    # Capture every call for assertions.
    calls: list[tuple[str, ClaudeCliOptions]] = field(default_factory=list)

    def preflight(self) -> None:
        return None

    async def run(
        self,
        prompt: str,
        options: ClaudeCliOptions,
        transcript_path: Path,
        *,
        dry_run: bool = False,
    ) -> ClaudeCliResult:
        self.calls.append((prompt, options))
        # Write the expected output file (mimic claude using the Write tool).
        if self.succeed and options.add_dirs:
            output_dir = options.add_dirs[0]
            output_dir.mkdir(parents=True, exist_ok=True)
            # The Stage tells claude where to save via append_system_prompt;
            # extract the path from there for the fake's behavior.
            # Heuristic: find the substring matching <output_dir>/.../NN-slug.md
            # We'll just write to a predictable path using the most recent call's dir.
            # In real tests the Stage already knows the path; here we mirror.
        return ClaudeCliResult(
            success=self.succeed,
            exit_code=0 if self.succeed else 1,
            duration_s=self.duration_s,
            raw_output=self.raw_output,
            error=self.error,
            session_id=options.session_id,
        )


@pytest.fixture
def minimal_config() -> dict[str, object]:
    return {
        'schema_version': 2,
        'batch_name': 'test-batch',
        'models': {'claude': {'model': 'claude-opus-4-7', 'effort': 'max'}},
        'runner': {
            'max_parallel_topics': 1,
            'max_retries_per_stage': 0,  # 1 attempt total — simple test
            'rate_limit_backoff_minutes': 0,
            'generic_failure_backoff_minutes': 0,
        },
        'topics': [
            {
                'id': '1',
                'slug': 'test-topic',
                'title': 'Test topic',
                'stages': {'claude': {'prompt': 'Research X comprehensively.'}},
            },
        ],
    }


class TestClaudeResearchStage:
    @pytest.mark.asyncio
    async def test_dry_run_succeeds_and_records_session(
        self, minimal_config: dict[str, object], tmp_path: Path
    ) -> None:
        cfg = load_batch_config(minimal_config)
        adapter = FakeClaudeAdapter(succeed=True)
        stage = ClaudeResearchStage(adapter=adapter)  # type: ignore[arg-type]

        # In dry_run, the orchestrator skips the existence check, so a fake
        # that doesn't actually write a file is fine.
        orch = Orchestrator(
            stage=stage,
            state_class=ClaudeResearchState,
            config=cfg,
            state_dir=tmp_path / 'state',
            output_dir=tmp_path / 'outputs',
            transcript_dir=tmp_path / 'transcripts',
            dry_run=True,
        )
        rc = await orch.run()

        assert rc == 0
        assert len(adapter.calls) == 1
        prompt, opts = adapter.calls[0]
        assert prompt == 'Research X comprehensively.'
        assert opts.model == 'claude-opus-4-7'
        assert opts.effort == 'max'
        assert opts.name == 'research-topic-1'
        assert 'Write tool' in (opts.append_system_prompt or '')
        # State file should exist with DONE status and recorded session_id.
        state = ClaudeResearchState.load_or_create(orch.state_dir, '1', 'test-topic')
        assert state.status is TopicStatus.DONE
        assert state.session_id == opts.session_id
        assert state.turn_1_duration_s == 1.0

    @pytest.mark.asyncio
    async def test_effort_defaults_to_max_when_config_omits_it(
        self, minimal_config: dict[str, object], tmp_path: Path
    ) -> None:
        # FM-4 (spec §6): ModelSpec.effort defaults to None. The typed refactor
        # must translate the old `models.get('effort', 'max')` to
        # `models.effort or 'max'`, NOT bare `models.effort` (which would pass
        # None). Config omits effort → the adapter must still receive 'max'.
        minimal_config['models'] = {'claude': {'model': 'claude-opus-4-7'}}
        cfg = load_batch_config(minimal_config)
        adapter = FakeClaudeAdapter(succeed=True)
        stage = ClaudeResearchStage(adapter=adapter)  # type: ignore[arg-type]
        orch = Orchestrator(
            stage=stage,
            state_class=ClaudeResearchState,
            config=cfg,
            state_dir=tmp_path / 'state',
            output_dir=tmp_path / 'outputs',
            transcript_dir=tmp_path / 'transcripts',
            dry_run=True,
        )
        await orch.run()

        _, opts = adapter.calls[0]
        assert opts.effort == 'max'

    @pytest.mark.asyncio
    async def test_real_output_path_pattern(
        self, minimal_config: dict[str, object], tmp_path: Path
    ) -> None:
        # Verify the Stage emits the canonical NN-slug.md filename pattern
        # (e.g., '01-test-topic.md' for topic id '1', slug 'test-topic').

        @dataclass
        class WritingFakeAdapter(FakeClaudeAdapter):
            """Fake adapter that actually writes the expected output file."""

            async def run(  # type: ignore[override]
                self,
                prompt: str,
                options: ClaudeCliOptions,
                transcript_path: Path,
                *,
                dry_run: bool = False,
            ) -> ClaudeCliResult:
                self.calls.append((prompt, options))
                # Extract the target output path from the save instruction.
                asp = options.append_system_prompt or ''
                # The Stage's instruction includes 'save the complete research
                # document to <path>'. Find that path (must end with .md).
                import re

                m = re.search(r'(\S+\.md)', asp)
                if m and self.succeed:
                    out = m.group(1)
                    from pathlib import Path as _Path

                    p = _Path(out)
                    p.parent.mkdir(parents=True, exist_ok=True)
                    p.write_text('# fake brief\n', encoding='utf-8')  # noqa: ASYNC240 — fake adapter for testing
                return ClaudeCliResult(
                    success=self.succeed,
                    exit_code=0 if self.succeed else 1,
                    duration_s=self.duration_s,
                    raw_output=self.raw_output,
                    error=self.error,
                    session_id=options.session_id,
                )

        cfg = load_batch_config(minimal_config)
        adapter = WritingFakeAdapter()
        stage = ClaudeResearchStage(adapter=adapter)  # type: ignore[arg-type]
        orch = Orchestrator(
            stage=stage,
            state_class=ClaudeResearchState,
            config=cfg,
            state_dir=tmp_path / 'state',
            output_dir=tmp_path / 'outputs',
            transcript_dir=tmp_path / 'transcripts',
        )
        rc = await orch.run()

        assert rc == 0
        expected_output = tmp_path / 'outputs' / '01-test-topic.md'
        assert expected_output.exists()
        state = ClaudeResearchState.load_or_create(orch.state_dir, '1', 'test-topic')
        assert state.status is TopicStatus.DONE
        assert state.research_file_bytes == expected_output.stat().st_size
